# Generated by Django 5.0.7 on 2024-08-21 11:40

import blog.models
import django.utils.timezone
import django_jalali.db.models
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_image_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='publish',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=75, scale=None, size=[500, 500], upload_to=blog.models.get_upload_to, verbose_name='تصویر'),
        ),
    ]
