# Generated by Django 5.0.7 on 2024-08-21 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_image_publish_alter_image_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='publish',
        ),
    ]
